"use client";

import React, { useState } from "react";
import { Shield, Activity, Zap, Download } from "lucide-react";
import { FinanceCard } from "@/components/ui/finance-card";
import { formatINR, formatINRCompact } from "@/lib/format";

export function StrategyTab({ stats }: { stats: any }) {
  const [riskProfile, setRiskProfile] = useState('moderate');
  
  const strategyDetails: any = {
    conservative: { 
      icon: Shield, 
      color: "text-blue-400",
      match: 92,
      advice: "Your portfolio is well-protected. Since you prefer stability, maintain a higher cash buffer and focus on debt instruments or liquid funds.",
      rebalance: 0.05
    },
    moderate: { 
      icon: Activity, 
      color: "text-primary",
      match: 84,
      advice: "You have a balanced approach. You are slightly over-exposed in Liquid Cash. Consider shifting some funds into diversified equity or index funds.",
      rebalance: 0.15
    },
    aggressive: { 
      icon: Zap, 
      color: "text-orange-400",
      match: 76,
      advice: "Growth is your priority. You have significant idle cash that could be working harder in high-growth equity or sectoral funds to beat inflation significantly.",
      rebalance: 0.3
    }
  };

  const currentStrategy = strategyDetails[riskProfile];

  const handleDownloadCSV = () => {
    const csvRows = [
      ["Finkar Financial Action Plan"],
      ["Date", new Date().toLocaleDateString()],
      ["Strategy Profile", riskProfile.toUpperCase()],
      [""],
      ["Asset Category", "Current Value", "Target Allocation (%)", "Recommended Action"],
      ["Liquid Cash", formatINR(stats.cash), riskProfile === 'conservative' ? "30%" : riskProfile === 'moderate' ? "15%" : "5%", "Reduce exposure, move to equity"],
      ["Stocks/MFs", formatINR(stats.portfolio.totalValue), riskProfile === 'conservative' ? "70%" : riskProfile === 'moderate' ? "85%" : "95%", "Increase holding in index funds"],
      [""],
      ["Immediate Priority", `Move ${formatINR(stats.netWorth * currentStrategy.rebalance)} into Equity`],
      ["Generated by Finkar AI"]
    ];

    const csvContent = "data:text/csv;charset=utf-8," + csvRows.map(e => e.join(",")).join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.body.appendChild(document.createElement("a"));
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Finkar_Action_Plan_${riskProfile}.csv`);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div className="flex flex-col gap-4">
        {['conservative', 'moderate', 'aggressive'].map((key) => {
          const detail = strategyDetails[key];
          const isSelected = riskProfile === key;
          return (
            <FinanceCard 
              key={key}
              onClick={() => setRiskProfile(key)}
              className={`p-5 cursor-pointer border-2 transition-all ${isSelected ? 'border-primary bg-primary/5 shadow-[0_0_20px_rgba(0,255,156,0.1)]' : 'border-border/50 hover:border-foreground/20 hover:bg-foreground/5'}`}
            >
              <div className="flex items-center gap-4">
                <div className={`p-3 rounded-xl bg-foreground/5 ${detail.color}`}>
                  <detail.icon size={20} />
                </div>
                <div>
                  <h4 className="text-sm font-black capitalize">{key}</h4>
                  <p className="text-[10px] text-muted-foreground mt-0.5">Rebalance for {key} growth.</p>
                </div>
              </div>
            </FinanceCard>
          );
        })}
      </div>

      <FinanceCard className="lg:col-span-2 p-6">
        <div className="flex justify-between items-center mb-6">
          <h3 className="font-heading font-bold">Optimization Summary</h3>
          <span className="text-[10px] font-black uppercase tracking-widest text-primary px-3 py-1 bg-primary/10 rounded-full">Recommended</span>
        </div>
        
        <div className="space-y-4">
          <div className="flex justify-between items-center p-4 rounded-xl bg-foreground/5 border border-border/50">
            <span className="text-sm font-bold">Current Alignment</span>
            <span className="text-sm text-muted-foreground">{currentStrategy.match}% Match</span>
          </div>
          <div className="p-5 border-l-4 border-primary bg-primary/[0.03]">
            <p className="text-xs leading-relaxed">
              Based on your <strong>{riskProfile}</strong> choice, {currentStrategy.advice} 
              Consider shifting <strong>{formatINRCompact(stats.netWorth * currentStrategy.rebalance)}</strong> into high-yield assets.
            </p>
          </div>
          <button 
            onClick={handleDownloadCSV}
            className="w-full mt-4 bg-primary text-primary-foreground font-black py-4 rounded-2xl flex items-center justify-center gap-2 hover:bg-primary/90 transition-all shadow-[0_4px_20px_rgba(0,255,156,0.2)] active:scale-[0.98]"
          >
            <Download size={18} /> Download Detailed Action Plan (CSV)
          </button>
        </div>
      </FinanceCard>
    </div>
  );
}
